### ISSUE TITLE
进入容器更新不了

### ISSUE THREAD

**Issue by houpi** [thesadboy/v2-ui-docker#3]
v2-ui主分支己更新，采用了xray内核。求更

另外我用
docker exec -it v2-ui /bin/bash
的方式进入容器内，运行v2-ui脚本的更新，秒提示更新成功（没有任何信息跑码）。但依然是旧版本的（在物理机状态下可以成功更新）。

**Comment by thesadboy** [comment]
已更新，另，实测容器内可更新。。。

**Comment by thesadboy** [comment]
最新版支持指定数据库目录，后续就不用每次更新镜像备份数据了，强烈支持使用最新版，之前版本记得将数据库备份出来
